dataiku/dataiku-contrib

tableau-export-v2/python-lib/tableau_utils.py
=> fix integer overflow error

datarendezvous/Makefile, datarendezvous/README.md, datarendezvous/plugin.json, datarendezvous/python-connectors/datarendezvous_dataset/connector.json, datarendezvous/python-connectors/datarendezvous_dataset/connector.py, datarendezvous/python-exporters/datarendezvous_exporter/exporter.json, datarendezvous/python-exporters/datarendezvous_exporter/exporter.py, datarendezvous/python-lib/datarendezvous_api.py
DataRendezVous connector experimental and initial version
Reads and write to/from DataRendezVous datalake
Added cosmetic changes and fixed Makefile
DataRendezVous will enhance the API client in future releases
=> few cosmetic changes on datarendezvous initial plugin

score-using-api-node/Makefile, score-using-api-node/custom-recipes/score-dataset/recipe.json, score-using-api-node/custom-recipes/score-dataset/recipe.py, score-using-api-node/plugin.json
Sends the content of a dataset to an API node for scoring, with the ability to unflatten the probability output.
=> Plugin to score a dataset using an API node

compare-datasets/Makefile, compare-datasets/custom-recipes/compute-difference/recipe.json, compare-datasets/custom-recipes/compute-difference/recipe.py, compare-datasets/plugin.json
Compares "value columns" of datasets by performing an outer join on "key columns"
=> Plugin to compare the content of two datasets

.gitignore, salesforce/Makefile, salesforce/README.md, salesforce/plugin.json, salesforce/python-connectors/salesforce-listview/connector.py, salesforce/python-connectors/salesforce-object/connector.py, salesforce/python-connectors/salesforce-objects/connector.py, salesforce/python-connectors/salesforce-query-results/connector.py, salesforce/python-connectors/salesforce-report/connector.json, salesforce/python-connectors/salesforce-report/connector.py
* Fixed: the number of rows returned by the plugin is now enforced (that fixes an issue with DSS 4.1.0)
* New: Report dataset (beta)
=> Plugin salesforce 1.1.0

sas-format/plugin.json, sas-format/python-formats/sas/format.json, sas-format/python-formats/sas/format.py
=> SAS format using Pandas

sentence-embedding/custom-recipes/sentence-embedding-similarity/recipe.json, sentence-embedding/custom-recipes/sentence-embedding-similarity/recipe.py, sentence-embedding/python-lib/sentence_embedding_utils.py
Added support for SIF aggregation method when using ELMO embeddings
=> Sentence embedding - Support for SIF with ELMO

image-segmentation/code-env/python/desc.json, image-segmentation/code-env/python/spec/requirements.txt, image-segmentation/custom-recipes/score_image/recipe.json, image-segmentation/custom-recipes/score_image/recipe.py, image-segmentation/plugin.json, image-segmentation/python-lib/coco/coco.py, image-segmentation/python-lib/mrcnn/config.py, image-segmentation/python-lib/mrcnn/model.py, image-segmentation/python-lib/mrcnn/parallel_model.py, image-segmentation/python-lib/mrcnn/utils.py, image-segmentation/python-lib/mrcnn/visualize.py, image-segmentation/python-lib/utils.py, image-segmentation/python-runnables/download-weights/runnable.json, image-segmentation/python-runnables/download-weights/runnable.py
initial commit, macro + plugin recipe using pre-trained maskRCNN model on COCO dataset.
1. Install plugin
2. create codenv
3. run macro to download weights
4. add recipe with 2 input folder : 1 with images to score and 1 with the model weights
=> image-segmentation plugin 

deeplearning-image-cpu/python-lib/api_designer_utils.py, deeplearning-image-cpu/python-runnables/create-api-service/runnable.json, deeplearning-image-cpu/python-runnables/create-api-service/runnable.py
Add macro to push a trained deep model from the plugin to an api service
=> Deeplearning image API deployment macro

geocoder/custom-recipes/forward_geocoding/recipe.json, geocoder/custom-recipes/reverse_geocoding/recipe.json
=> typo: entreprise -> enterprise

clear-intermediate-datasets/plugin.json, clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.json, clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.py
Found this cool macro made by PierreP, added a few tweaks:
- option to exclude shared datasets
- a bit of refactoring
- logging
- some aesthetics
=> Clear intermediate datasets (improved version)

dataproc-clusters/Makefile, dataproc-clusters/README.md, dataproc-clusters/code-env/python/desc.json, dataproc-clusters/code-env/python/spec/requirements.txt, dataproc-clusters/plugin.json, dataproc-clusters/python-clusters/dataproc-attach-to-existing-cluster/cluster.json, dataproc-clusters/python-clusters/dataproc-attach-to-existing-cluster/cluster.py, dataproc-clusters/python-clusters/dataproc-create-cluster/cluster.json, dataproc-clusters/python-clusters/dataproc-create-cluster/cluster.py, dataproc-clusters/python-lib/dku_dataproc.py, dataproc-clusters/python-lib/gce_client.py, dataproc-clusters/python-runnables/get-cluster-info/runnable.json, dataproc-clusters/python-runnables/get-cluster-info/runnable.py, dataproc-clusters/python-runnables/scale-cluster/runnable.json, dataproc-clusters/python-runnables/scale-cluster/runnable.py
This plugin is ment to create or use existing Dataproc Hadoop clusters  with DSS. 
WIP....
=> Dataproc multicluster

push-project-to-automation/python-runnables/dataiku_project_or_bundle_migration/runnable.json, push-project-to-automation/python-runnables/dataiku_project_or_bundle_migration/runnable.py
Added a new button to ignore SSL certifications on the remote dss api client
=> Added ignore SSL certs option to project bundle migration macro

dataproc-clusters/Makefile, dataproc-clusters/python-clusters/dataproc-attach-to-existing-cluster/cluster.json, dataproc-clusters/python-clusters/dataproc-create-cluster/cluster.json
Few UI tweaks to have something coherent and a bit closer to the cluster creation form in the GCP console.
=> DataProc plugin small improvements

sentiment-analysis/custom-recipes/sentiment-analysis-score/recipe.py
fixing case error on fastText -> fasttext, see: https://pypi.org/project/fasttext/
Unsure why we are installing from git instead of pypi. Did not change but should be considered.
=> fixing import error with sentiment analysis plugin

mapbox-maps-backgrounds/Makefile, mapbox-maps-backgrounds/js/mapbox.js, mapbox-maps-backgrounds/plugin.json
settings retrieval now requires a HTTP call
=> update mapbox plugin for settings retrieval

wms-maps-backgrounds/Makefile, wms-maps-backgrounds/js/wms.js, wms-maps-backgrounds/parameter-sets/wms-service/parameter-set.json, wms-maps-backgrounds/plugin.json
- fixes the retrieval of plugin settings in the WMS plugin (settings are retrieved by a js snippet)
- adds a parameter set with clearly defined fields to replace the old 'everything-in-a-text-field' approach
=> Fix wms plugin for DSS 6+

excel-importer/code-env/python/desc.json, excel-importer/python-runnables/macro-excel-importer/runnable.py
https://app.clubhouse.io/dataiku/story/42400/dataset-from-folder-metrics-engine-failed-to-run
=> Excel-importer

project-deployer/python-runnables/dataiku_project_or_bundle_migration/runnable.py
Fixing a bug in the plugin. Previously, in cases where the remote project did not already exist on the automation node, any code environments used in the design node project would not get pushed.
=> Fixing projct creation python environment bug per Jed

wikipedia-pageviews/Makefile, wikipedia-pageviews/code-env/python/desc.json, wikipedia-pageviews/custom-recipes/wikipedia-pageviews-masspages/recipe.json, wikipedia-pageviews/custom-recipes/wikipedia-pageviews-masspages/recipe.py, wikipedia-pageviews/plugin.json, wikipedia-pageviews/python-connectors/wikipedia-pageviews-pagesperday/connector.py, wikipedia-pageviews/python-connectors/wikipedia-pageviews-topperday/connector.py
* Add code-env and support for py3
=> Wikipedia pageviews/improvement

text-summarization/Makefile, text-summarization/code-env/python/desc.json, text-summarization/custom-recipes/text-summarization-compute/recipe.json, text-summarization/custom-recipes/text-summarization-compute/recipe.py, text-summarization/plugin.json
* Add support for py3 (tested)
* Make the plugin mus-compatible (no write in the home directory)
=> Text summarization/improvement

sas-format/Makefile, sas-format/code-env/python/desc.json, sas-format/plugin.json, sas-format/python-formats/sas/format.py
* Add code-env
* Add support for py3 (tested)
=> Sas format/improvement

census-us/Makefile, census-us/Readme.md, census-us/code-env/python/desc.json, census-us/custom-recipes/address-batch-geocoder-us-census-geo/recipe.json, census-us/custom-recipes/address-batch-geocoder-us-census-geo/recipe.py, census-us/custom-recipes/generate-census-with-feature-selection/recipe.json, census-us/custom-recipes/generate-census-with-feature-selection/recipe.py, census-us/custom-recipes/get-block-from-lat-lon/recipe.json, census-us/custom-recipes/get-block-from-lat-lon/recipe.py, census-us/plugin.json, census-us/python-connectors/census-us_us_census_custom_dataset/connector.json, census-us/python-connectors/census-us_us_census_custom_dataset/connector.py, census-us/python-connectors/census_metadata/connector.json, census-us/python-connectors/census_metadata/connector.py, census-us/python-lib/census_metadata.py, census-us/python-lib/census_resources.py, census-us/python-lib/common.py, census-us/python-lib/geocoder_utils.py
* New version of Nicolas
* Add support for py3 (tested)
=> Census-us/Improvement

dataset-audit/Makefile, dataset-audit/custom-recipes/dataset-audit-sqlike/recipe.py, dataset-audit/plugin.json
* Fix misc bugs
* Add support for py3 
https://app.clubhouse.io/dataiku/story/43591/dataset-audit-query-fail
https://app.clubhouse.io/dataiku/story/43592/dataset-audit-incompatible-syntax-with-py3
=> Dataset audit/improvement

clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.json, clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.py, clear-intermediate-datasets/resources/get_projects.py
This is a PR to parametrize the current macro. In its current form it only clears datasets in the current project, but in order to use in a wider admin setting it should be able to take in a parameter. 
If the parameter is not populated, it will default to current behaviour and target current project.
=> Clear datasets params

gutenberg/Makefile, gutenberg/plugin.json, gutenberg/python-connectors/gutenberg-project-book/connector.json, gutenberg/python-connectors/gutenberg-project-book/connector.py
Gutenberg appears to have changed their URLs.  I tested this fix and it creates the dataset.  Not sure of the full process for improving a plugin.
=> Fix gutenberg download URL

clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.py
- To improve clarity, the table now shows not only the datasets that will be kept but also those to clear
- Clear datasets show now on the top
- The columns have been restructured for more clarity, including the state of the action (dry run vs done)
- Added more logging info
Includes fixes to all comments in previous [pull request](https://github.com/dataiku/dataiku-contrib/pull/222)
=> Update result table output of the clear-intermediate-datasets macro

clear-intermediate-datasets/python-runnables/clear_int_datasets/runnable.py
Previously, datasets not linked to a flow would be considered intermediate and cleared
=> Added standalone category
